[project]
name = "noodles-classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "rich>=14.2.0",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
]
